### ISSUE TITLE
Recommended way to handle variants of variants?

### ISSUE THREAD

**Issue by whaaaley** [rstacruz/rscss#42]
I'm a little confused about how to handle variants of variants in a good way. This probably isn't _that_ common, but sometimes it's nice to have a variant with some options too.

---

This is the best way I could think of handling it, but there's a rule about how **not** to use dashes in variant names. Maybe this could be a use case?

``` scss
.component-name {
  &.-variant {
    padding: em($padding);

    &-large { @extend #{&}; @include scale(1.5); }
    &-small { @extend #{&}; @include scale(0.75); }
  }

  &.-another {
    // ...
  }
}
```

``` html
<div class='component-name -variant'></div>
<div class='component-name -variant-small'></div>
<div class='component-name -variant-large'></div>
```

---

This is another way but this could be confused about what is a modifier of what...

``` scss
.component-name {
  &.-variant {
    padding: em($padding);

    &.-large { @include scale(1.5); }
    &.-small { @include scale(0.75); }
  }

  &.-another {
    // ...
  }
}
```

``` html
<div class='component-name -variant'></div>
<div class='component-name -variant -small'></div>
<div class='component-name -variant -large'></div>
```

**Comment by rstacruz** [comment]
Interesting. In your use case, it's probably best to make `.component-name.-variant` be a separate component.

It makes sense to mix-and-match variants:
- Color variants: `-danger` `-success`
- Size variants: `-small` `-medium` `-large` `-massive`

``` html
<div class='submit-button -danger -large'></div>
<div class='submit-button -danger -small'></div>
<div class='submit-button -success -medium'></div>
```

It can make sense to define how certain variants interact when declared together:

``` css
/* Big red buttons should glow! */
.submit-button.-massive.-danger {
  box-shadow: 0 0 10px red;
}
```

But this can get very hairy at some point:

``` css
/* Big red buttons should glow! */
.submit-button.-massive.-danger { ... }

/* Big green buttons should have a checkmark */
.submit-button.-massive.-success::before { ... }

/* Big disabled buttons should have different font styles */
.submit-button.-massive:disabled { ... }
```

At that point, it seems that `-massive` is too complicated to be a variant, and it may be time to make a `.massive-submit-button` component.

Let me know if that helps!
