### ISSUE TITLE
Starting classes with - (hypen) not advised

### ISSUE THREAD

**Issue by localpcguy** [rstacruz/rscss#8]
I'm glad you address that "starting classes with a hypen" may be hard for some to do.  Either as an additional caveat in that section, or perhaps to consider revising altogether, it should be noted that per the CSS spec, while it is valid to start a class with a hyphen, it limits your next character to a letter.

> In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-z0-9] and ISO 10646 characters U+00A1 and higher, plus the hyphen (-) and the underscore (_); **they cannot start with** a digit, or **a hyphen followed by a digit**. 

There could also be confusion with the recommendation that beginning a identifier with a hyphen be reserved in keywords and property names, but that doesn't specifically apply to classes.

> In CSS, identifiers may begin with '-' (dash) or '_' (underscore). Keywords and property names beginning with '-' or '_' are reserved for vendor-specific extensions.

**Comment by jamesmacfie** [comment]
There's also potential for conflict based on multiple classes on a component, each with identical modifiers.

Silly example to show what I mean:

``` scss
.button {
  background-color: blue;

  &.-red {
    background-color: red;
  }

  &.-large {
    height: 50px;
  }
}

.error {
  color: red;

  &.-large {
    font-size: 40px;
  }
}
```

``` html
<button class="button -red -large error">Delete</button>
```

What do we expect in the above? Does the user want it to be both a large button plus large text? Or did they just want the large button without the large text? 

Like I said, silly example, but it shows that there's the potential for error there. Just one of the reasons that BEM has the class name it's modifying combined with the modifier class name itself.
